package com.pvsrishabh.momentshub.utils

const val USER_NODE = "User"
const val USER_PROFILE_FOLDER = "ProfileImage"
const val POST_FOLDER = "PostImages"
const val REEL_FOLDER = "PostVideos"
const val POST = "Post"
const val REEL = "Reel"
const val STORY = "Story"
const val FOLLOW = "Follow"
const val FOLLOWERS = "Followers"
const val CHAT = "Chats"
const val LIKE = "Like"
const val REELLIKE = "ReelLike"
const val STORYLIKE = "StoryLike"
const val SAVE = "Save"
const val MESSAGE_FOLDER = "Message"